-- ============================================================================
-- Weekly client reports (migration 067)
--
-- Purpose:
--   Persists the weekly pipeline report the cron builds for every client, so
--   that:
--     1. Clients see their report history on /client/reports (dashboard).
--     2. AEs can download any week's report as a clean PDF to send manually.
--     3. The report survives even after underlying opportunities are
--        archived or deleted (snapshot semantics via the jsonb payload).
--
-- Design notes:
--   * One row per (client_id, week_start) — UNIQUE constraint makes the cron
--     idempotent: re-running the same week UPSERTs instead of duplicating.
--   * `week_start` is ALWAYS a Monday (the first day of the reported week).
--     The cron runs Monday 09:00 UTC and reports on the PREVIOUS week.
--   * `payload` is a self-contained snapshot (stage counts, recent leads,
--     KPIs). Buyer names inside the payload are already MASKED at build time
--     (mirrors client_leads_masked: identity hidden before price_agreed,
--     contact details hidden before shipped) — the same rules as R-07.
--   * Writes happen ONLY from the service role (cron / API route that already
--     authenticated the caller). No INSERT/UPDATE policies are created, so
--     RLS denies writes for normal users by default.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.client_weekly_reports (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id    uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  -- Monday of the reported week (ISO week start)
  week_start   date NOT NULL,
  -- Reported window (week_start .. week_start + 6 days), kept explicit so
  -- the dashboard can render "24/08 – 30/08" without recomputing.
  period_start date NOT NULL,
  period_end   date NOT NULL,
  -- Snapshot of the report content (masked buyer names, KPIs, stage counts).
  payload      jsonb NOT NULL,
  -- Delivery bookkeeping for the cron.
  email_sent   boolean NOT NULL DEFAULT false,
  email_error  text,
  created_at   timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT client_weekly_reports_week_unique UNIQUE (client_id, week_start)
);

-- Recent-first listing per client (dashboard + AE download list).
CREATE INDEX IF NOT EXISTS idx_client_weekly_reports_client
  ON public.client_weekly_reports(client_id, week_start DESC);

ALTER TABLE public.client_weekly_reports ENABLE ROW LEVEL SECURITY;

-- 1) Clients can read their OWN reports.
DROP POLICY IF EXISTS "client_weekly_reports_select_own" ON public.client_weekly_reports;
CREATE POLICY "client_weekly_reports_select_own"
  ON public.client_weekly_reports
  FOR SELECT
  TO authenticated
  USING (auth.uid() = client_id);

-- 2) Admin-shell roles can read everything (AE scoping to owned clients is
--    enforced at the application layer — same pattern as notifications).
DROP POLICY IF EXISTS "client_weekly_reports_admin_all" ON public.client_weekly_reports;
CREATE POLICY "client_weekly_reports_admin_all"
  ON public.client_weekly_reports
  FOR SELECT
  TO authenticated
  USING (
    public.get_current_user_role() IN (
      'super_admin', 'admin', 'staff', 'finance',
      'account_executive', 'lead_researcher'
    )
  );

COMMENT ON TABLE public.client_weekly_reports IS
  'Weekly pipeline report snapshots per client. Generated by the /api/cron/weekly-report job. '
  'Payloads contain pre-masked buyer names (R-07 disclosure rules). Writes are service-role only.';
